# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\learn_words_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Learn_Words_Window(object):
    def setupUi(self, Learn_Words_Window):
        Learn_Words_Window.setObjectName("Learn_Words_Window")
        Learn_Words_Window.resize(800, 435)
        Learn_Words_Window.setStyleSheet("background-color: rgb(252, 252, 189);")
        self.centralwidget = QtWidgets.QWidget(Learn_Words_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.table_words = QtWidgets.QTableWidget(self.centralwidget)
        self.table_words.setGeometry(QtCore.QRect(20, 20, 461, 401))
        self.table_words.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_words.setObjectName("table_words")
        self.table_words.setColumnCount(2)
        self.table_words.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_words.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        item.setFont(font)
        self.table_words.setHorizontalHeaderItem(1, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 20, 271, 41))
        self.label.setStyleSheet("background-color: rgb(168, 168, 168);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(490, 70, 271, 41))
        self.spinBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.spinBox.setObjectName("spinBox")
        self.btn_output_in_order = QtWidgets.QPushButton(self.centralwidget)
        self.btn_output_in_order.setGeometry(QtCore.QRect(490, 130, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_output_in_order.setFont(font)
        self.btn_output_in_order.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_output_in_order.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_output_in_order.setStyleSheet("QPushButton {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: none;\n"
"    color: #0000;\n"
"    padding: 8px 16px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 170, 0);\n"
"    padding-left: 14px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_output_in_order.setAutoRepeatInterval(100)
        self.btn_output_in_order.setObjectName("btn_output_in_order")
        self.btn_output_in_diffrent = QtWidgets.QPushButton(self.centralwidget)
        self.btn_output_in_diffrent.setGeometry(QtCore.QRect(490, 220, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_output_in_diffrent.setFont(font)
        self.btn_output_in_diffrent.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_output_in_diffrent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_output_in_diffrent.setStyleSheet("QPushButton {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: none;\n"
"    color: #0000;\n"
"    padding: 8px 16px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 170, 0);\n"
"    padding-left: 14px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_output_in_diffrent.setAutoRepeatInterval(100)
        self.btn_output_in_diffrent.setObjectName("btn_output_in_diffrent")
        Learn_Words_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Learn_Words_Window)
        QtCore.QMetaObject.connectSlotsByName(Learn_Words_Window)

    def retranslateUi(self, Learn_Words_Window):
        _translate = QtCore.QCoreApplication.translate
        Learn_Words_Window.setWindowTitle(_translate("Learn_Words_Window", "MainWindow"))
        item = self.table_words.horizontalHeaderItem(0)
        item.setText(_translate("Learn_Words_Window", "Слово"))
        item = self.table_words.horizontalHeaderItem(1)
        item.setText(_translate("Learn_Words_Window", "Перевод"))
        self.label.setText(_translate("Learn_Words_Window", "Сколько вывести слов?"))
        self.btn_output_in_order.setText(_translate("Learn_Words_Window", "Вывести по порядку"))
        self.btn_output_in_diffrent.setText(_translate("Learn_Words_Window", "Вывести в разнобой"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Learn_Words_Window = QtWidgets.QMainWindow()
    ui = Ui_Learn_Words_Window()
    ui.setupUi(Learn_Words_Window)
    Learn_Words_Window.show()
    sys.exit(app.exec_())
