# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 294)
        MainWindow.setStyleSheet("background-color: rgb(252, 252, 189);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(149, 190, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_open_learn_words = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_learn_words.setGeometry(QtCore.QRect(90, 70, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_learn_words.setFont(font)
        self.btn_open_learn_words.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_open_learn_words.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_open_learn_words.setStyleSheet("QPushButton {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: none;\n"
"    color: #0000;\n"
"    padding: 8px 16px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 170, 0);\n"
"    padding-left: 14px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_open_learn_words.setAutoRepeatInterval(100)
        self.btn_open_learn_words.setObjectName("btn_open_learn_words")
        self.btn_open_translate_words = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_translate_words.setGeometry(QtCore.QRect(90, 140, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_translate_words.setFont(font)
        self.btn_open_translate_words.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_open_translate_words.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_open_translate_words.setStyleSheet("QPushButton {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: none;\n"
"    color: #0000;\n"
"    padding: 8px 16px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 170, 0);\n"
"    padding-left: 14px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_open_translate_words.setAutoRepeatInterval(100)
        self.btn_open_translate_words.setObjectName("btn_open_translate_words")
        self.btn_open_currect_words = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_currect_words.setGeometry(QtCore.QRect(90, 210, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_currect_words.setFont(font)
        self.btn_open_currect_words.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_open_currect_words.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_open_currect_words.setStyleSheet("QPushButton {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: none;\n"
"    color: #0000;\n"
"    padding: 8px 16px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 170, 0);\n"
"    padding-left: 14px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_open_currect_words.setAutoRepeatInterval(100)
        self.btn_open_currect_words.setObjectName("btn_open_currect_words")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        self.menu_app = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.menu_app.setFont(font)
        self.menu_app.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.menu_app.setObjectName("menu_app")
        self.menu = QtWidgets.QMenu(self.menu_app)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menu.setFont(font)
        self.menu.setStyleSheet("background-color: rgb(182, 182, 182);")
        self.menu.setObjectName("menu")
        self.menu_words = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.menu_words.setFont(font)
        self.menu_words.setStyleSheet("background-color: rgb(182, 182, 182);")
        self.menu_words.setObjectName("menu_words")
        MainWindow.setMenuBar(self.menubar)
        self.for_creator_app = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.for_creator_app.setFont(font)
        self.for_creator_app.setObjectName("for_creator_app")
        self.for_learn_words = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.for_learn_words.setFont(font)
        self.for_learn_words.setObjectName("for_learn_words")
        self.for_translate_words = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.for_translate_words.setFont(font)
        self.for_translate_words.setObjectName("for_translate_words")
        self.for_correct_words = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.for_correct_words.setFont(font)
        self.for_correct_words.setObjectName("for_correct_words")
        self.action_words = QtWidgets.QAction(MainWindow)
        self.action_words.setObjectName("action_words")
        self.action_delete_words = QtWidgets.QAction(MainWindow)
        self.action_delete_words.setObjectName("action_delete_words")
        self.info_about_add_delete = QtWidgets.QAction(MainWindow)
        self.info_about_add_delete.setObjectName("info_about_add_delete")
        self.menu.addAction(self.for_learn_words)
        self.menu.addAction(self.for_translate_words)
        self.menu.addAction(self.for_correct_words)
        self.menu.addSeparator()
        self.menu.addAction(self.info_about_add_delete)
        self.menu_app.addAction(self.menu.menuAction())
        self.menu_app.addAction(self.for_creator_app)
        self.menu_words.addAction(self.action_words)
        self.menubar.addAction(self.menu_app.menuAction())
        self.menubar.addAction(self.menu_words.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное окно"))
        self.label.setText(_translate("MainWindow", "Приложение для изучения английских слов"))
        self.btn_open_learn_words.setText(_translate("MainWindow", "Учить слова"))
        self.btn_open_translate_words.setText(_translate("MainWindow", "Перевод слов"))
        self.btn_open_currect_words.setText(_translate("MainWindow", "Правильность написания"))
        self.menu_app.setTitle(_translate("MainWindow", "Информация"))
        self.menu.setTitle(_translate("MainWindow", "О приложении"))
        self.menu_words.setTitle(_translate("MainWindow", "Слова"))
        self.for_creator_app.setText(_translate("MainWindow", "О создателе"))
        self.for_learn_words.setText(_translate("MainWindow", "Вкладка \"учить слова\""))
        self.for_translate_words.setText(_translate("MainWindow", "Вкладка \"перевод слов\""))
        self.for_correct_words.setText(_translate("MainWindow", "Вкладка \"правильность написания\""))
        self.action_words.setText(_translate("MainWindow", "Добавить/Удалить"))
        self.action_delete_words.setText(_translate("MainWindow", "Удалить слова"))
        self.info_about_add_delete.setText(_translate("MainWindow", "Вкладка добавить/удалить слова"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
