# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\translate_words_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Translate_Window(object):
    def setupUi(self, Translate_Window):
        Translate_Window.setObjectName("Translate_Window")
        Translate_Window.resize(800, 505)
        Translate_Window.setStyleSheet("background-color: rgb(252, 252, 189);")
        self.centralwidget = QtWidgets.QWidget(Translate_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.radio_basic = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_basic.setGeometry(QtCore.QRect(10, 70, 381, 31))
        self.radio_basic.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.radio_basic.setChecked(True)
        self.radio_basic.setObjectName("radio_basic")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 220, 801, 31))
        self.line.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 191, 41))
        self.label.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(161, 161, 161);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.radio_faster = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_faster.setGeometry(QtCore.QRect(10, 120, 371, 31))
        self.radio_faster.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.radio_faster.setCheckable(True)
        self.radio_faster.setObjectName("radio_faster")
        self.radio_on_total = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_on_total.setGeometry(QtCore.QRect(10, 170, 371, 31))
        self.radio_on_total.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.radio_on_total.setObjectName("radio_on_total")
        self.btn_start_end = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_end.setGeometry(QtCore.QRect(510, 10, 261, 191))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start_end.setFont(font)
        self.btn_start_end.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_start_end.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_start_end.setStyleSheet("QPushButton {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: none;\n"
"    color: #0000;\n"
"    padding: 8px 16px;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 170, 0);\n"
"    padding-left: 14px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_start_end.setAutoRepeatInterval(100)
        self.btn_start_end.setObjectName("btn_start_end")
        self.timer_label = QtWidgets.QLabel(self.centralwidget)
        self.timer_label.setGeometry(QtCore.QRect(10, 260, 71, 41))
        self.timer_label.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"")
        self.timer_label.setText("")
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.edit_to_out = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_to_out.setGeometry(QtCore.QRect(170, 270, 401, 51))
        self.edit_to_out.setStyleSheet("font: italic 20pt \"Times New Roman\";")
        self.edit_to_out.setText("")
        self.edit_to_out.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_to_out.setDragEnabled(False)
        self.edit_to_out.setReadOnly(True)
        self.edit_to_out.setObjectName("edit_to_out")
        self.edit_to_input = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_to_input.setGeometry(QtCore.QRect(170, 350, 401, 51))
        self.edit_to_input.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.edit_to_input.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_to_input.setDragEnabled(False)
        self.edit_to_input.setReadOnly(True)
        self.edit_to_input.setObjectName("edit_to_input")
        self.btn_accept = QtWidgets.QPushButton(self.centralwidget)
        self.btn_accept.setGeometry(QtCore.QRect(610, 350, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_accept.setFont(font)
        self.btn_accept.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_accept.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_accept.setStyleSheet("QPushButton {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: none;\n"
"    color: #0000;\n"
"    padding: 8px 16px;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 170, 0);\n"
"    padding-left: 14px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_accept.setAutoRepeatInterval(100)
        self.btn_accept.setObjectName("btn_accept")
        self.btn_skip_word = QtWidgets.QPushButton(self.centralwidget)
        self.btn_skip_word.setGeometry(QtCore.QRect(610, 270, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_skip_word.setFont(font)
        self.btn_skip_word.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_skip_word.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_skip_word.setStyleSheet("QPushButton {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: none;\n"
"    color: #0000;\n"
"    padding: 8px 16px;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 170, 0);\n"
"    padding-left: 14px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_skip_word.setAutoRepeatInterval(100)
        self.btn_skip_word.setObjectName("btn_skip_word")
        Translate_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Translate_Window)
        QtCore.QMetaObject.connectSlotsByName(Translate_Window)

    def retranslateUi(self, Translate_Window):
        _translate = QtCore.QCoreApplication.translate
        Translate_Window.setWindowTitle(_translate("Translate_Window", "MainWindow"))
        self.radio_basic.setText(_translate("Translate_Window", "Обычный"))
        self.label.setText(_translate("Translate_Window", "Режимы"))
        self.radio_faster.setText(_translate("Translate_Window", "На скорость"))
        self.radio_on_total.setText(_translate("Translate_Window", "Вывести определенное количество"))
        self.btn_start_end.setText(_translate("Translate_Window", "Начать"))
        self.edit_to_out.setPlaceholderText(_translate("Translate_Window", "Слово"))
        self.edit_to_input.setPlaceholderText(_translate("Translate_Window", "Введите перевод слова выше"))
        self.btn_accept.setText(_translate("Translate_Window", "Отправить"))
        self.btn_skip_word.setText(_translate("Translate_Window", "Пропустить\n"
"слово"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Translate_Window = QtWidgets.QMainWindow()
    ui = Ui_Translate_Window()
    ui.setupUi(Translate_Window)
    Translate_Window.show()
    sys.exit(app.exec_())
