# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\delete_words_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Words_Window(object):
    def setupUi(self, Words_Window):
        Words_Window.setObjectName("Words_Window")
        Words_Window.resize(835, 395)
        Words_Window.setStyleSheet("background-color: rgb(252, 252, 189);")
        self.centralwidget = QtWidgets.QWidget(Words_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.table_words = QtWidgets.QTableWidget(self.centralwidget)
        self.table_words.setGeometry(QtCore.QRect(10, 20, 521, 361))
        self.table_words.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_words.setObjectName("table_words")
        self.table_words.setColumnCount(3)
        self.table_words.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_words.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_words.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        item.setFont(font)
        self.table_words.setHorizontalHeaderItem(2, item)
        self.btn_delete_word = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete_word.setGeometry(QtCore.QRect(550, 80, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete_word.setFont(font)
        self.btn_delete_word.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_delete_word.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_delete_word.setStyleSheet("QPushButton {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: none;\n"
"    color: #0000;\n"
"    padding: 8px 16px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 170, 0);\n"
"    padding-left: 14px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_delete_word.setAutoRepeatInterval(100)
        self.btn_delete_word.setObjectName("btn_delete_word")
        self.btn_change_word = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_word.setGeometry(QtCore.QRect(550, 140, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_change_word.setFont(font)
        self.btn_change_word.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_change_word.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_change_word.setStyleSheet("QPushButton {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: none;\n"
"    color: #0000;\n"
"    padding: 8px 16px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 170, 0);\n"
"    padding-left: 14px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_change_word.setAutoRepeatInterval(100)
        self.btn_change_word.setObjectName("btn_change_word")
        self.btn_add_word = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_word.setGeometry(QtCore.QRect(550, 20, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_word.setFont(font)
        self.btn_add_word.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_add_word.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_add_word.setStyleSheet("QPushButton {\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: none;\n"
"    color: #0000;\n"
"    padding: 8px 16px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 170, 0);\n"
"    padding-left: 14px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.btn_add_word.setAutoRepeatInterval(100)
        self.btn_add_word.setObjectName("btn_add_word")
        Words_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Words_Window)
        QtCore.QMetaObject.connectSlotsByName(Words_Window)

    def retranslateUi(self, Words_Window):
        _translate = QtCore.QCoreApplication.translate
        Words_Window.setWindowTitle(_translate("Words_Window", "MainWindow"))
        item = self.table_words.horizontalHeaderItem(0)
        item.setText(_translate("Words_Window", "id"))
        item = self.table_words.horizontalHeaderItem(1)
        item.setText(_translate("Words_Window", "Слово"))
        item = self.table_words.horizontalHeaderItem(2)
        item.setText(_translate("Words_Window", "Перевод"))
        self.btn_delete_word.setText(_translate("Words_Window", "Удалить слово"))
        self.btn_change_word.setText(_translate("Words_Window", "Изменить слово/перевод"))
        self.btn_add_word.setText(_translate("Words_Window", "Добавить слово"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Words_Window = QtWidgets.QMainWindow()
    ui = Ui_Words_Window()
    ui.setupUi(Words_Window)
    Words_Window.show()
    sys.exit(app.exec_())
